deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: develop
before_install:
- openssl aes-256-cbc -K $encrypted_96718c21863f_key -iv $encrypted_96718c21863f_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
