language: node_js
deploy:
  provider: script
  script: bash -x .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
script: npm -v
addons:
  ssh_known_hosts:
  - 94.130.180.129
before_install:
- openssl aes-256-cbc -K $encrypted_45457958fdd0_key -iv $encrypted_45457958fdd0_iv
  -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
